name: test_tapped
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
